kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: docker:latest
    commands:
      - docker build -t test .
    volumes:
      - name: docker-socket
        path: /var/run/docker.sock
    when:
      branch: main

services:
  - name: dind
    image: docker:dind
    privileged: true

volumes:
  - name: docker-socket
    host:
      path: /var/run/docker.sock