steps:
  - name: build
    image: docker:latest
    privileged: true  # Necessario per l'accesso al socket
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock