kind: pipeline
type: docker
name: build

services:
  - name: docker
    image: docker:dind

steps:
  - name: costruzione-immagine
    image: docker
    commands:
      - docker build -t test:latest .
