kind: pipeline
type: docker
name: build

steps:
  - name: "Costruzione immagine Docker"
    image: docker:stable-dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock  # Usa il socket Docker della macchina host
    commands:
      - docker build -t test .