kind: pipeline
type: docker
name: build-and-test

# Configurazione per Docker-in-Docker
services:
  dind:
    image: docker:dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""  # Disabilita TLS

steps:
  - name: build
    image: docker:latest
    environment:
      DOCKER_HOST: tcp://dind:2375  # Collega al servizio DinD
    commands:
      - docker build -t test .
      - docker run test