kind: pipeline
type: docker
name: build

steps:
 - name: "Costruzione immagine Docker"
   image: docker:stable-dind
   privileged: true  # Abilita il modalità privilegiata
   commands:
   - docker build -t test:latest .