kind: pipeline
type: docker
name: build

steps:
  - name: costruzione-immagine
    image: gcr.io/kaniko-project/executor:latest
    environment:
      DOCKER_CONFIG: "/kaniko/.docker"
    commands:
      - mkdir -p /kaniko/.docker
      - echo "{\"auths\":{}}" > /kaniko/.docker/config.json
      - /kaniko/executor
        --context=.
        --dockerfile=Dockerfile
        --destination=test:latest