kind: pipeline
type: docker
name: build

steps:
  - name: costruzione-immagine
    image: docker:latest
    volumes:
      - name: docker-socket
        path: /var/run/docker.sock
    commands:
      - docker build -t test:latest .

volumes:
  - name: docker-socket
    host:
      path: /var/run/docker.sock