kind: pipeline
type: docker
name: build

services:
  - name: docker
    image: docker:dind
    environment:
      DOCKER_TLS_CERTDIR: "/certs"  # Configurazione sicura per Docker-in-Docker

steps:
  - name: costruzione-immagine
    image: docker:latest
    commands:
      - docker build -t test:latest .
