name: Test ARC Runner

on: [push]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Print Hello
        run: echo "Hello from MicroK8s ARC runner!"
