name: Build, Push and Deploy

on:
  push:
    branches:
      - main  # Modifica se necessario

jobs:
  build_push_deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login a Harbor
        run: |
          docker login ${{ secrets.localhost }} \
            -u ${{ secrets.admin }} \
            -p ${{ secrets.Harbor12345 }}

      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ secrets.localhost }}/namespace/app:${{ github.sha }}
          docker build -t $IMAGE_TAG .

      - name: Push Docker image
        run: |
          IMAGE_TAG=${{ secrets.localhost }}/namespace/app:${{ github.sha }}
          docker push $IMAGE_TAG

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy to microk8s
        run: |
          kubectl set image deployment/app-deployment app=${{ secrets.localhost }}/namespace/app:${{ github.sha }} --record
          kubectl rollout status deployment/app-deployment
